import type { Metadata } from "next";
import "./globals.css";
import Aside from "@/components/conestants/Aside";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        {/* <Header /> */}
        <div className="flex min-h-screen  ">
          <Aside />
          {children}
        </div>
      </body>
    </html>
  );
}
